blog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name='blog'
urlpatterns = [
    path('', views.blog, name='blog'),
    path('<str:slug>', views.blog_post, name='blogpost'),
]

dashboard/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name= 'dashboard'
urlpatterns = [
    path('', views.home, name='home'),
    path('contact/', views.contact_form, name='contact_form'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

personalwebsite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dashboard.urls', namespace="dashboard")),
    path('todolist/', include('todolist.urls', namespace="todolist")),
    path('blog/', include("blog.urls", namespace="blog")),
]

todolist/urls.py
from django.urls import path
from . import views


app_name='todolist'
urlpatterns = [
    path('', views.home_todo, name='home_todo'),
    path('delete/<str:pk>', views.delete_todo, name='delete_todo'),
]

weather/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.weather, name='weather'),
]

blog/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    id= models.AutoField(primary_key=True)
    title= models.CharField(max_length=50)
    content= models.TextField()
    author= models.CharField(max_length=20)
    slug= models.CharField(max_length=50)
    timeStamp= models.DateTimeField(auto_now_add=True, blank=True)

    def __str__(self) -> str:
        return self.title + ' - ' + self.author

dashboard/models.py
from django.db import models

# Create your models here.
class Contact(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=25)
    phone = models.CharField(max_length=20)
    email = models.CharField(max_length=50)
    content = models.TextField()
    timeStamp = models.DateTimeField(auto_now_add=True, blank=True)

    def __str__(self) -> str:
        return self.name + ' - ' + self.email

todolist/models.py
from django.db import models

class Todo(models.Model):
    title = models.CharField(max_length=200)

    @classmethod
    def get_all_todo(cls):
        return cls.objects.all()
    
    @classmethod
    def create_todo(cls, title):
        new_todo = cls(title=title)
        new_todo.save()

    @classmethod
    def delete_todo(cls, todo_id):
        todo = cls.objects.get(id=todo_id)
        todo.delete()
         
    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render
from .models import Post

# Create your views here.
def blog(request):
    allPosts =  Post.objects.all()
    context = {'allPosts': allPosts}
    return render(request, 'blog.html', context)

def blog_post(request, slug):
    post = Post.objects.filter(slug=slug).first()
    context= {'post': post}
    return render(request, 'blog-post.html', context)

dashboard/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .models import Contact


# Create your views here.
def contact_form(request):
    if request.method == "POST":
        name = request.POST.get('name', '')
        email = request.POST.get('email', '') 
        phone = request.POST.get('phone', '')
        content = request.POST.get('content', '')
        if len(name) < 2 or len(email) < 3 or len(phone) < 10 or len(content) < 4:
            messages.error(request, " Please fill out the form as required")
        else:
            contact= Contact(name=name, email=email, phone=phone, content=content)
            contact.save()
            messages.success(request, " Your message has been sent")
    
    return render(request, 'contact-me.html')

def home(request):
    return render(request, 'home.html')

todolist/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from .models import Todo
from .utils import handle_post_request
from .weather_utils import get_weather_data


# Create your views here.
def delete_todo(request, pk):
    Todo.delete_todo(pk)
    return redirect(reverse('todolist:home_todo'))

def home_todo(request):
    city_name = None
    if request.method == 'POST':
        city_name = handle_post_request(request)

    if city_name == None:
        city_name = request.session.get('last_searched_city', "Tel Aviv")

    all_todos = Todo.get_all_todo()
    weather_data = get_weather_data(city_name)

    data = {
        "city": weather_data['city'],
        'weather_now': weather_data['weather_now'],
        "temperature": weather_data['temperature'],
        "feels_like": weather_data['feels_like'],
        "humidity": weather_data['humidity'],
        "todos": all_todos
    }

    return render(request, 'todolist.html', data)

weather/views.py
from django.shortcuts import render
from decouple import config
import json
import requests


# Create your views here.
def weather(request):
    queryUrl = "https://api.openweathermap.org/data/2.5/weather?q=tel aviv&"
    apiOptions = "units=metric&exclude=minutely,alerts&"
    apiKey = "appid=" + config("WEATHER_API_KEY")
    url = queryUrl + apiOptions + apiKey
    list_of_data = requests.get(url).json()
    data= {
        "Sunrise": str(list_of_data['sys']['sunrise']),
        "Sunset": str(list_of_data['sys']['sunset']),
        "Tempeture": round((list_of_data['main']['temp'])),
        "Feels like": round((list_of_data['main']['feels_like'])),
        "humidity": str(list_of_data['main']['humidity']),            
    }
    return render(request, "weather.html", data)

def weather2(request):
    if request.method == 'POST':
        city= request.POST['city']
        source = "https://api.openweathermap.org/data/2.5/weather?q={}&units=imperial&appid="
        list_of_data = requests.get(source.format(city)).json()
        data= {
            "country_code": str(list_of_data['sys']['country']),
            "coordinate": str(list_of_data['coord']['lon']) + ' ' + str(list_of_data['coord']['lat']),
            "temp": round((list_of_data['main']['temp']-32)* 5.0/9.0, 2),
            "humidity": str(list_of_data['main']['humidity']),            
        }
    else:
        data= {}
    return render(request, "weather.html", data)

        # // Backgrounds
        # switch (main) {
        # case "Snow":
        # document.getElementById("wrapper-bg").style.backgroundImage =
        # "url('https://mdbgo.io/ascensus/mdb-advanced/img/snow.gif')";
        # break;
        # case "Clouds":
        # document.getElementById("wrapper-bg").style.backgroundImage =
        # "url('https://mdbgo.io/ascensus/mdb-advanced/img/clouds.gif')";
        # break;
        # case "Fog":
        # document.getElementById("wrapper-bg").style.backgroundImage =
        # "url('https://mdbgo.io/ascensus/mdb-advanced/img/fog.gif')";
        # break;
        # case "Rain":
        # document.getElementById("wrapper-bg").style.backgroundImage =
        # "url('https://mdbgo.io/ascensus/mdb-advanced/img/rain.gif')";
        # break;
        # case "Clear":
        # document.getElementById("wrapper-bg").style.backgroundImage =
        # "url('https://mdbgo.io/ascensus/mdb-advanced/img/clear.gif')";
        # break;
        # case "Thunderstorm":
        # document.getElementById("wrapper-bg").style.backgroundImage =
        # "url('https://mdbgo.io/ascensus/mdb-advanced/img/thunderstorm.gif')";
        # break;
        # default:
        # document.getElementById("wrapper-bg").style.backgroundImage =
        # "url('https://mdbgo.io/ascensus/mdb-advanced/img/clear.gif')";
        # break;
        # }

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %} {% endblock %} - Personal Website</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'dashboard/style.css' %}">
    {% block head %}{% endblock %}
  </head>
  <body>
    <nav class="navbar navbar-expand-lg mb-5">
      <div class="container-fluid">
        <span class="navbar-brand">Personal-Website</span>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link {% block homeactive %} {% endblock %}" href="{% url 'dashboard:home' %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link {% block todoactive %} {% endblock %}" href="{% url 'todolist:home_todo' %}">My Todo</a>
            </li>
            <li class="nav-item">
              <a class="nav-link {% block blogactive %} {% endblock %}" href="{% url 'blog:blog' %}">Blog</a>
            </li>
            <li class="nav-item">
              <a class="nav-link {% block contactactive %} {% endblock %}" href="{% url 'dashboard:contact_form' %}">Contact Me</a>
            </li>
            <li class="nav-item dropdown position-absolute end-0">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Settings</a>
              <ul class="dropdown-menu dropdown-menu-end">
                <li><a class="dropdown-item" href="/admin">Admin Panel</a></li>
                <li><a class="dropdown-item" href="#">Logout</a></li>
                <li><a class="dropdown-item" href="#">Free Slot</a></li>
              </ul>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    {% block body %} {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  </body>
</html>

templates/blog-post.html
{% extends 'base.html' %}
{% block title %} Blog {% endblock %}
{% block blogactive %} active {% endblock %}
{% block body %}
    <article class="container">
        <h2 class="blog-post-title mb-1">{{post.title}}</h2>
        <p class="blog-post-meta">{{post.timeStamp}} by <a href="/about">{{post.author}}</a></p>
        <p>{{post.content}}</p>
    </article>
{% endblock %}

templates/blog.html
{% extends 'base.html' %}
{% block title %} Blog {% endblock %}
{% block blogactive %} active {% endblock %}
{% block body %}
    <form action="/blog-post" method="get" class="d-flex" role="search">
        <input name="query" class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
    </form>
    {% for post in allPosts %}
    <div class="container my-3">
    <div class="card">
        <div class="card-body">
        <h8 class="card-author">Blog by - {{post.author}}</h8>
        <h5 class="card-title">{{post.title}}</h5>
        <p class="card-text">{{post.content | truncatechars:100}}</p>
        <a href="{{post.slug}}" class="btn btn-primary">Read More</a>
        </div> 
    </div>
    </div>  
    {% endfor %} 
{% endblock %}

templates/contact-me.html
{% extends 'base.html' %}
{% block title %} Contact Me {% endblock %}
{% block head %} {% endblock %}
{% block contactctive %} active {% endblock %}
{% block body %}
<div class="container mb-1">
    <!-- Contact Section -->
        {% for message in messages %}
        <!-- Display error messages only if the form is submitted -->
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
            <strong>Message:</strong>{{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>   
        {% endfor %}
</div>    
<div class="container container-spacing">
    <h2>Contact me:</h2>
    <form action="" method="post">
    {% csrf_token %}
    {{ contact_form.as_p }}
    <div class="mb-3">
        <label for="name" class="form-label">Name</label>
        <input type="text" class="form-control" name="name" id="name" aria-describedby="name">
    </div>
    <div class="mb-3">
        <label for="email" class="form-label">Email</label>
        <input type="email" class="form-control" name="email" id="email" aria-describedby="email">
    </div>
    <div class="mb-3">
        <label for="phone" class="form-label">Phone</label>
        <input type="phone" class="form-control" name="phone" id="phone">
    </div>
    <div class="mb-3">
        <label for="content" class="form-label">Message</label>
        <textarea class="form-control" id="content" name="content" cols="30" rows="5"></textarea>
    </div>
    <button type="submit" name="btn_contact_form" class="btn btn-primary">Submit</button>
    </form>
    </div> 
{% endblock %}

templates/home.html
{% extends 'base.html' %}
{% block title %} Home {% endblock %} 
{% block head%}{% endblock %} 
{% block homeactive %} active {% endblock %} 
{% block body %}
<div class="container">
  <!-- Cover Photo -->
  {% load static %}
  <img src="{% static 'dashboard/NoBadDay.jpg' %}" class="cover-photo rounded" />
  <!-- Profile Section -->
  <div class="profile-section">
    <!-- Profile Photo -->
    <div class="profile-photo">
      {% load static %}
      <img src="{% static 'dashboard/Portfolio1.jpg' %}" class="profile-photo" />
    </div>
    <!-- Profile-Information -->
    <div class="about-me">
      <h3>Hey, I'm Gal David</h3>
      <p>
        A Software Developer Focusing on Web Development and Automation, and I'm ready
        to turn your challenges into opportunities!
      </p>
    </div>
  </div>
</div>
{% endblock %}

templates/todolist.html
{% extends 'base.html' %}
{% block title %} Todo List {% endblock %}
{% block todoactive %} active {% endblock %}
{% block head %} {% endblock %}
{% block body %}
<div class="container">
<!-- Todo List Section -->
<div class="container todo-section">
  <h2>Things i have to do!</h2>
  <form action="{% url 'todolist:home_todo' %}" method="POST">
    {% csrf_token %}
    <input type="text" name="title" id="myInput" placeholder="Create new task" />
    <button type="submit" class="btn todo-btn">Add</button>
  </form>
  <ul class="todo-list">
    {% for todo in todos reversed %}
    <li>
      <span>{{ todo.title | title }}</span>
      <span><a class="btn delete-btn" href="delete/{{todo.id}}">Delete</a></span>
    </li>
    {% endfor %}
  </ul>
</div>
<!-- Weather Section -->
<div class="container weather-section">
  <h3>Check the Weather Forecast</h3>
  <form class="d-flex" method="post" action="{% url 'todolist:home_todo' %}">
    {% csrf_token %}
    <input class="form-control me-2" type="search" name="city_name" placeholder="Enter a city" aria-label="Search" />
    <button class="btn weather-search-btn" name="btn_weather_form" type="submit">
      Search
    </button>
  </form>
  <div class="card shadow-0 border mt-3">
    <div class="card-body p-4">
      <h4 class="mb-1 fw-normal">{{ city | title }} - <span class="text-muted">{{ weather_now }}</span></h4>
      <p class="mb-2">
        Temperature: <strong>{{ temperature }}°C</strong>&nbsp;&nbsp;&nbsp;Humidity: <strong>{{ humidity }}%</strong>
      </p>
      <p>Feels Like: <strong>{{ feels_like }}°C</strong></p>
  </div>
</div>

</div>

{% endblock %}